FROM sail-8.4/app

WORKDIR /var/www/html

# Set Git safe directory
RUN git config --global --add safe.directory /var/www/html

# Set the user to the same as Laravel Sail's default user
USER sail

# Copy the entire application code into the container
COPY . .

# Install dependencies and cache configuration
RUN composer install --no-dev --optimize-autoloader
RUN php artisan config:cache

# Command to run the WebSocket listener
# CMD ["php", "artisan", "phemex:listen-websocket"]
